---
sudo: required

git:
    submodules: false

language: c

services:
  - docker

before_install:
  - git submodule init
  - git submodule update &
  - GITPID=$!
  - while kill -0 $GITPID 2>/dev/null; do echo "Waiting for clone"; sleep 30; done;
  - ./.clear-builder-cache
  - mkdir dist
  - docker build -f Dockerfile.srpm-builder -t atgreen/moxielogic-srpm-builder .
  - docker run -t -v `pwd`:/opt atgreen/moxielogic-srpm-builder
  - rm -f dist/*.tar.gz dist/*.spec dist/*.patch
  - docker build -f Dockerfile.builder-el7 -t atgreen/moxielogic-builder-el7 .

script:
  - ls -l

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push atgreen/moxielogic-builder-el7;
    fi
  - ./.trigger

