sudo: required

language: c

services:
  - docker

before_install:
  - git submodule sync
  - git submodule update --init
  - mkdir dist
  - docker build -f Dockerfile.f24 -t moxielogic/moxiedev-builder-f24 .
  - docker run -t -v `pwd`:/opt moxielogic/moxiedev-builder-f24
  - find rpms -name \*.rpm
  - echo DONE


