---
sudo: required

language: c

services:
  - docker

before_install:
  - curl -X DELETE -H 'Authorization: token $TRAVIS_TOKEN' https://api.travis-ci.org/repos/atgreen/moxiedev-builder/caches
  - mkdir dist
  - docker build -f Dockerfile.srpm-builder -t atgreen/moxiedev-srpm-builder .
  - docker run -t -v `pwd`:/opt atgreen/moxiedev-srpm-builder
  - rm -f dist/*.tar.gz dist/*.spec dist/*.patch
  - docker build -f Dockerfile.repos -t atgreen/moxielogic-repos .

script:
  -

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push atgreen/moxielogic-repos;
    fi
  - ./.trigger

