FROM fedora

MAINTAINER green@moxielogic.org

RUN dnf -y install \
    gcc gcc-c++ rpm-build make patch autoconf automake mpfr-devel \
    gmp-devel libmpc-devel flex bison rpm-build zlib-devel \
    python-devel texinfo ncurses-devel createrepo

CMD cd /opt && ./scripts/mksrpm.sh && ./scripts/mkrpms.sh





