FROM docker.io/centos:7

MAINTAINER green@moxielogic.org

RUN yum -y install \
    gcc gcc-c++ rpmbuild make patch autoconf automake mpfr-devel \
    libgmp-devel mpc-devel flex bison rpm-build zlib-devel \
    python-devel texinfo ncurses-devel createrepo gperf

CMD cd /opt && ./scripts/mksrpm.sh && echo "**BUILDING - see build-el7.log for logs**" && set -o pipefail && (./scripts/mkrpms.sh 2>1 | tee build-el7.log)






