# Base image for the f26 builder.  Build this manually and upload to
# docker hub in order to avoid build time dependencies on Fedora
# repos.

FROM docker.io/fedora:26

MAINTAINER green@moxielogic.org

RUN dnf clean all \
    && dnf -y update \
    && dnf -y install gcc gcc-c++ rpm-build make patch autoconf \
       	      automake mpfr-devel gmp-devel libmpc-devel flex \
	      bison zlib-devel python-devel texinfo ncurses-devel \
	      createrepo gperf \
    && dnf clean all
    
